name: getx
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.8
    dio: ^5.4.0
    permission_handler: ^11.3.0
    path_provider: ^2.1.2
    open_file: ^3.3.2
    wallpaper_manager_flutter: ^1.0.1
    flutter_downloader: ^1.11.4
    http: ^1.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

dependency_overrides:
    async: ^2.13.0
    fake_async: ^1.3.3
    leak_tracker: ^11.0.1
    leak_tracker_flutter_testing: ^3.0.10
    leak_tracker_testing: ^3.0.2
    lints: ^6.0.0
    material_color_utilities: ^0.12.0
    meta: ^1.17.0
    test_api: ^0.7.6
    vector_math: ^2.2.0
    vm_service: ^15.0.1

flutter:
    uses-material-design: true

    assets:
        - assets/
